server:
  port: 4083

logging:
  level:
    com:
      hedvig: DEBUG

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
      javax:
        persistence:
          schema-generation:
            create-source: metadata
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson:
    serialization:
      write_dates_as_timestamps: false

  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    region:
      static: eu-central-1
    credentials.useDefaultAwsCredentialsChain: true
    stack:
      auto: false
