server:
  port: 4083

logging:
  level:
    com:
      hedvig: DEBUG

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
      javax:
        persistence:
          schema-generation:
            create-source: metadata
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson:
    serialization:
      write_dates_as_timestamps: false
