server:
  port: 4083

logging:
  level:
    com:
      hedvig: DEBUG

hedvig:
  kafka:
    acks: all
    retries: 3
    bootstrap:
      servers: localhost:9092
      schema:
        registry:
          url: http://localhost:8081

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            create-source: metadata
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson:
    serialization:
      write_dates_as_timestamps: false
